# Generated by Django 3.2.7 on 2021-09-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_listing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='img',
            field=models.ImageField(blank=True, upload_to='static/team/%Y/%m/%d'),
        ),
    ]
