# Generated by Django 3.2.7 on 2021-09-21 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_team_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='close',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='name',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='open',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='state',
        ),
    ]
